const data = {
  products: [
    {
      name: 'Nike slim pants',
      slug: 'nike-slim-shirt',
      category: 'shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      branch: 'Nike',
      rating: 4.5,
      numReviews: 10,
      descriptions: 'high quality shirt',
    },
    {
        name: 'Addidas slim pants',
        slug: 'Addidas-slim-shirt',
        category: 'shirts',
        image: '/images/p2.jpg',
        price: 120,
        countInStock: 10,
        branch: 'Addidas',
        rating: 4.5,
        numReviews: 10,
        descriptions: 'high quality shirt',
      },
      {
        name: 'puma slim pants',
        slug: 'puma-slim-shirt',
        category: 'shirts',
        image: '/images/p3.jpg',
        price: 120,
        countInStock: 10,
        branch: 'puma',
        rating: 4.5,
        numReviews: 10,
        descriptions: 'high quality shirt',
      },
      {
        name: 'Loiu Vuiton slim pants',
        slug: 'Loiu Vuiton-slim-shirt',
        category: 'shirts',
        image: '/images/p4.jpg',
        price: 120,
        countInStock: 10,
        branch: 'Loiu Vuiton',
        rating: 4.5,
        numReviews: 10,
        descriptions: 'high quality shirt',
      },
  ],
};

export default data;